# nixpacks.toml (Versión a prueba de balas)

[phases.setup]
# Le decimos explícitamente que instale python Y la herramienta pip
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
# Ahora que estamos seguros de que pip existe, ejecutamos el comando de instalación
cmds = ["python -m pip install -r requirements.txt"]

[start]
# El comando para iniciar la aplicación (este no cambia)
cmd = "python -m gunicorn app:app"